import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signInSubtitle': 'Sign in to your account',
    'auth.signUpSubtitle': 'Sign up to get started',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.loading': 'Loading...',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.noAccount': "Don't have an account? Sign up",
    'auth.haveAccount': "Already have an account? Sign in",
    'auth.testAccount': 'Test Account:',
    'auth.error': 'Error',
    'auth.success': 'Success',
    'auth.confirmEmail': 'Please check your email to confirm your account.',
    
    // Dashboard
    'dashboard.title1': 'Select a desirable good to',
    'dashboard.title2': 'let your',
    'dashboard.title2.money': 'money',
    'dashboard.title2.rest': 'work for you',
    'dashboard.withdrawable': 'Withdrawable Principle',
    'dashboard.returns': 'Returns',
    'dashboard.investment': 'Investment Progress',
    'dashboard.days': 'Days',
    'dashboard.until': 'Until the next free',
    'dashboard.starbucks': 'Starbucks',
    'dashboard.withdraw': 'Withdraw Principle',
    'dashboard.addPurchases': 'Add New Purchases',
    'dashboard.privacy': 'Privacy Policy',
    'dashboard.userAgreement': 'User Agreement',
    'dashboard.resetTitle': 'Reset All Investments?',
    'dashboard.resetDescription': 'This will permanently delete all your investments and history. This action cannot be undone.',
    'dashboard.cancel': 'Cancel',
    'dashboard.reset': 'Reset',
    'dashboard.resetComplete': 'Reset Complete',
    'dashboard.resetSuccess': 'All investments have been cleared.',
    'dashboard.error': 'Error',
    'dashboard.resetFailed': 'Failed to reset investments.',
    'dashboard.apyTitle': 'YOUR ANNUAL PAY YIELD (APY)',
    'dashboard.higherThanBoJ': 'higher than BoJ!',
    'dashboard.feeStructure': 'Fee Structure',
    'dashboard.feeDescription': 'Our management fee is 1% baseline + 20% of the remaining returns.',
    'dashboard.feeExample': 'Example: Asset APY',
    'dashboard.managementFee': 'Management Fee',
    'dashboard.yourAPY': 'Your APY',
    'dashboard.dynamicRate': 'Dynamic Rate',
    'dashboard.dynamicRateDescription': 'This APY updates in real-time based on lending rates across Decentralized Finance (DeFi) protocols and changes constantly with market conditions.',
    'dashboard.loadingAPY': 'Loading APY data...',
    'dashboard.apyError': 'Unable to load APY data',
    'dashboard.pending': 'Pending',
    'dashboard.noInvestments': 'No ongoing investment. Select a desirable good to start having your money work for you.',
    'dashboard.returnsDialogTitle': 'Your Returns',
    'dashboard.returnsDialogDescription': 'View your APY and fee structure details',
    
    // Pick Purchase
    'pickPurchase.title1': 'Select a desirable good to',
    'pickPurchase.title2': 'let your',
    'pickPurchase.title2.money': 'money',
    'pickPurchase.title2.rest': 'work for you',
    'pickPurchase.pick': 'Pick a purchase',
    'pickPurchase.eggs': 'Eggs (10 units)',
    'pickPurchase.milk': 'Milk',
    'pickPurchase.yogurt': 'Yogurt',
    'pickPurchase.beer': 'Beer (6 cans)',
    'pickPurchase.rice': 'Rice (2 kg)',
    'pickPurchase.cigarette': 'Cigarette',
    'pickPurchase.coffee': 'Coffee (Regular)',
    
    // Decide Deposit
    'decideDeposit.title1': 'Select a desirable good to',
    'decideDeposit.title2': 'let your',
    'decideDeposit.title2.money': 'money',
    'decideDeposit.title2.rest': 'work for you',
    'decideDeposit.decide': 'Decide your deposit',
    'decideDeposit.selected': 'Selected Item',
    'decideDeposit.netflix': 'Netflix',
    'decideDeposit.starbucks': 'Starbucks',
    'decideDeposit.eggs': 'Eggs (10 units)',
    'decideDeposit.milk': 'Milk',
    'decideDeposit.yogurt': 'Yogurt',
    'decideDeposit.beer': 'Beer (6 cans)',
    'decideDeposit.rice': 'Rice (2 kg)',
    'decideDeposit.cigarette': 'Cigarette',
    'decideDeposit.coffee': 'Coffee (Regular)',
    'decideDeposit.deposit': 'Deposit',
    'decideDeposit.payback': 'Pay back in',
    'decideDeposit.aiRec': 'AI Recommendation',
    'decideDeposit.nextStep': 'Next step',
    'decideDeposit.addMore': 'Add more recurring purchases',
    'decideDeposit.min': 'Min:',
    'decideDeposit.max': 'Max:',
    'decideDeposit.get': 'Get 1',
    'decideDeposit.free': 'free',
    'decideDeposit.by': 'by',
    'decideDeposit.depositing': 'depositing',
    'decideDeposit.today': 'today',
    'decideDeposit.aiRecText': 'Depositing',
    'decideDeposit.toGetFree': 'to get a free',
    'decideDeposit.eachDay': 'each day',
    'decideDeposit.eachWeek': 'each week',
    'decideDeposit.eachMonth': 'each month',
    'decideDeposit.eachYear': 'each year',
    'decideDeposit.every': 'every',
    'decideDeposit.days': 'days',
    'decideDeposit.months': 'months',
    'decideDeposit.years': 'years',
    
    // Payment Method
    'paymentMethod.title1': 'Select a desirable good to',
    'paymentMethod.title2': 'let your',
    'paymentMethod.title2.money': 'money',
    'paymentMethod.title2.rest': 'work for you',
    'paymentMethod.selectPayment': 'Select payment method',
    'paymentMethod.selected': 'Selected Item',
    'paymentMethod.netflix': 'Netflix',
    'paymentMethod.deposit': 'Deposit',
    'paymentMethod.payback': 'Pay back in',
    'paymentMethod.summary': 'Summary of your offer',
    'paymentMethod.paymentTitle': 'How do you want to deposit?',
    'paymentMethod.bankWire': 'Bank Wire',
    'paymentMethod.stablecoin': 'Stablecoin',
    'paymentMethod.creditCard': 'Credit Card',
    'paymentMethod.get': 'Get 1',
    'paymentMethod.free': 'free',
    'paymentMethod.by': 'by',
    'paymentMethod.depositing': 'depositing',
    'paymentMethod.today': 'today',
    
    // Payment Process
    'paymentProcess.featureAvailable': 'Feature available soon.',
    'paymentProcess.sendUsdc': 'Send',
    'paymentProcess.usdcAmount': 'amount of USDC to the address below.',
    'paymentProcess.finishPayment': 'Finish Payment',
    'paymentProcess.investmentCreated': 'Investment Created!',
    'paymentProcess.investmentCreatedSuccess': 'Your {product} investment has been created successfully.',
    'paymentProcess.error': 'Error',
    'paymentProcess.createFailed': 'Failed to create investment. Please try again.',
    'paymentProcess.investmentUpdated': 'Investment Updated',
    'paymentProcess.addedToInvestment': 'Added ￥{amount} to your {product} investment. Countdown reset.',
    'paymentProcess.withdrawFunds': 'Withdraw Funds',
    'paymentProcess.withdrawDescription': 'Please withdraw ￥{amount} from your existing {product} investment to reduce it.',
    'paymentProcess.noChanges': 'No Changes',
    'paymentProcess.noChangesDescription': 'Your {product} investment amount is the same.',
    'paymentProcess.updateFailed': 'Failed to update investment. Please try again.',
    'paymentProcess.updateExisting': 'Update Existing Investment?',
    'paymentProcess.duplicateDescription': 'You already have an investment for {product} with ￥{amount} deposited. Would you like to update your existing investment?',
    'paymentProcess.cancel': 'Cancel',
    'paymentProcess.update': 'Update',
  },
  ja: {
    // Auth
    'auth.welcomeBack': 'おかえりなさい',
    'auth.createAccount': 'アカウント作成',
    'auth.signInSubtitle': 'アカウントにサインイン',
    'auth.signUpSubtitle': 'サインアップして始める',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.enterEmail': 'メールアドレスを入力',
    'auth.enterPassword': 'パスワードを入力',
    'auth.loading': '読み込み中...',
    'auth.signIn': 'サインイン',
    'auth.signUp': 'サインアップ',
    'auth.noAccount': 'アカウントをお持ちでないですか？サインアップ',
    'auth.haveAccount': 'すでにアカウントをお持ちですか？サインイン',
    'auth.testAccount': 'テストアカウント：',
    'auth.error': 'エラー',
    'auth.success': '成功',
    'auth.confirmEmail': 'メールを確認してアカウントを認証してください。',
    
    // Dashboard
    'dashboard.title1': '欲しい商品を選んで',
    'dashboard.title2': 'あなたの',
    'dashboard.title2.money': 'お金',
    'dashboard.title2.rest': 'を働かせましょう',
    'dashboard.withdrawable': '引き出し可能な元本',
    'dashboard.returns': 'リターン',
    'dashboard.investment': '投資進捗',
    'dashboard.days': '日',
    'dashboard.until': '次の無料',
    'dashboard.starbucks': 'スターバックス',
    'dashboard.withdraw': '元本を引き出す',
    'dashboard.addPurchases': '新しい購入を追加',
    'dashboard.privacy': 'プライバシーポリシー',
    'dashboard.userAgreement': '利用規約',
    'dashboard.resetTitle': 'すべての投資をリセットしますか？',
    'dashboard.resetDescription': 'これにより、すべての投資と履歴が完全に削除されます。この操作は元に戻せません。',
    'dashboard.cancel': 'キャンセル',
    'dashboard.reset': 'リセット',
    'dashboard.resetComplete': 'リセット完了',
    'dashboard.resetSuccess': 'すべての投資がクリアされました。',
    'dashboard.error': 'エラー',
    'dashboard.resetFailed': '投資のリセットに失敗しました。',
    'dashboard.apyTitle': '年間利回り（APY）',
    'dashboard.higherThanBoJ': '日銀より高い！',
    'dashboard.feeStructure': '手数料体系',
    'dashboard.feeDescription': '管理手数料は基本1%＋残りのリターンの20%です。',
    'dashboard.feeExample': '例：資産APY',
    'dashboard.managementFee': '管理手数料',
    'dashboard.yourAPY': 'あなたのAPY',
    'dashboard.dynamicRate': '動的レート',
    'dashboard.dynamicRateDescription': 'このAPYは、分散型金融（DeFi）プロトコル全体の貸付金利に基づいてリアルタイムで更新され、市場状況に応じて常に変動します。',
    'dashboard.loadingAPY': 'APYデータを読み込み中...',
    'dashboard.apyError': 'APYデータを読み込めません',
    'dashboard.pending': '保留中',
    'dashboard.noInvestments': '進行中の投資はありません。お金を働かせるために、希望する商品を選択してください。',
    'dashboard.returnsDialogTitle': 'あなたのリターン',
    'dashboard.returnsDialogDescription': 'APYと手数料体系の詳細を表示',
    
    // Pick Purchase
    'pickPurchase.title1': '欲しい商品を選んで',
    'pickPurchase.title2': 'あなたの',
    'pickPurchase.title2.money': 'お金',
    'pickPurchase.title2.rest': 'を働かせましょう',
    'pickPurchase.pick': '購入を選択',
    'pickPurchase.eggs': '卵（10個）',
    'pickPurchase.milk': '牛乳',
    'pickPurchase.yogurt': 'ヨーグルト',
    'pickPurchase.beer': 'ビール（6缶）',
    'pickPurchase.rice': '米（2kg）',
    'pickPurchase.cigarette': 'タバコ',
    'pickPurchase.coffee': 'コーヒー（レギュラー）',
    
    // Decide Deposit
    'decideDeposit.title1': '欲しい商品を選んで',
    'decideDeposit.title2': 'あなたの',
    'decideDeposit.title2.money': 'お金',
    'decideDeposit.title2.rest': 'を働かせましょう',
    'decideDeposit.decide': '預金額を決める',
    'decideDeposit.selected': '選択されたアイテム',
    'decideDeposit.netflix': 'ネットフリックス',
    'decideDeposit.starbucks': 'スターバックス',
    'decideDeposit.eggs': '卵（10個）',
    'decideDeposit.milk': '牛乳',
    'decideDeposit.yogurt': 'ヨーグルト',
    'decideDeposit.beer': 'ビール（6缶）',
    'decideDeposit.rice': '米（2kg）',
    'decideDeposit.cigarette': 'タバコ',
    'decideDeposit.coffee': 'コーヒー（レギュラー）',
    'decideDeposit.deposit': '預金',
    'decideDeposit.payback': '返済期間',
    'decideDeposit.aiRec': 'AI推奨',
    'decideDeposit.nextStep': '次のステップ',
    'decideDeposit.addMore': '定期購入を追加',
    'decideDeposit.min': '最小：',
    'decideDeposit.max': '最大：',
    'decideDeposit.get': '',
    'decideDeposit.free': '無料',
    'decideDeposit.by': 'で',
    'decideDeposit.depositing': '',
    'decideDeposit.today': '今日',
    'decideDeposit.aiRecText': '',
    'decideDeposit.toGetFree': 'を預けて無料の',
    'decideDeposit.eachDay': '毎日',
    'decideDeposit.eachWeek': '毎週',
    'decideDeposit.eachMonth': '毎月',
    'decideDeposit.eachYear': '毎年',
    'decideDeposit.every': '毎',
    'decideDeposit.days': '日',
    'decideDeposit.months': 'ヶ月',
    'decideDeposit.years': '年',
    
    // Payment Method
    'paymentMethod.title1': '欲しい商品を選んで',
    'paymentMethod.title2': 'あなたの',
    'paymentMethod.title2.money': 'お金',
    'paymentMethod.title2.rest': 'を働かせましょう',
    'paymentMethod.selectPayment': '決済方法を選択',
    'paymentMethod.selected': '選択されたアイテム',
    'paymentMethod.netflix': 'ネットフリックス',
    'paymentMethod.deposit': '預金',
    'paymentMethod.payback': '返済期間',
    'paymentMethod.summary': 'オファーの概要',
    'paymentMethod.paymentTitle': 'どのように預金しますか？',
    'paymentMethod.bankWire': '銀行送金',
    'paymentMethod.stablecoin': 'ステーブルコイン',
    'paymentMethod.creditCard': 'クレジットカード',
    'paymentMethod.get': '',
    'paymentMethod.free': '無料',
    'paymentMethod.by': 'で',
    'paymentMethod.depositing': '',
    'paymentMethod.today': '今日',
    
    // Payment Process
    'paymentProcess.featureAvailable': '機能は間もなく利用可能です。',
    'paymentProcess.sendUsdc': '',
    'paymentProcess.usdcAmount': 'USDCを以下のアドレスに送金してください。',
    'paymentProcess.finishPayment': '支払いを完了',
    'paymentProcess.investmentCreated': '投資が作成されました！',
    'paymentProcess.investmentCreatedSuccess': '{product}の投資が正常に作成されました。',
    'paymentProcess.error': 'エラー',
    'paymentProcess.createFailed': '投資の作成に失敗しました。もう一度お試しください。',
    'paymentProcess.investmentUpdated': '投資が更新されました',
    'paymentProcess.addedToInvestment': '{product}の投資に￥{amount}を追加しました。カウントダウンがリセットされました。',
    'paymentProcess.withdrawFunds': '資金を引き出す',
    'paymentProcess.withdrawDescription': '既存の{product}投資から￥{amount}を引き出して減額してください。',
    'paymentProcess.noChanges': '変更なし',
    'paymentProcess.noChangesDescription': '{product}の投資額は同じです。',
    'paymentProcess.updateFailed': '投資の更新に失敗しました。もう一度お試しください。',
    'paymentProcess.updateExisting': '既存の投資を更新しますか？',
    'paymentProcess.duplicateDescription': 'すでに{product}の投資があり、￥{amount}が預けられています。既存の投資を更新しますか？',
    'paymentProcess.cancel': 'キャンセル',
    'paymentProcess.update': '更新',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
