import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.signInSubtitle': 'Sign in to your account',
    'auth.signUpSubtitle': 'Sign up to get started',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.loading': 'Loading...',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.noAccount': "Don't have an account? Sign up",
    'auth.haveAccount': "Already have an account? Sign in",
    'auth.testAccount': 'Test Account:',
    'auth.error': 'Error',
    'auth.success': 'Success',
    'auth.confirmEmail': 'Please check your email to confirm your account.',
    
    // Dashboard
    'dashboard.title1': 'Select a desirable good to',
    'dashboard.title2': 'let your',
    'dashboard.title2.money': 'money',
    'dashboard.title2.rest': 'work for you',
    'dashboard.withdrawable': 'Withdrawable Principle',
    'dashboard.returns': 'Returns',
    'dashboard.investment': 'Investment Progress',
    'dashboard.days': 'Days',
    'dashboard.until': 'Until the next free',
    'dashboard.starbucks': 'Starbucks',
    'dashboard.startInvesting': 'Start Investing',
    'dashboard.withdraw': 'Withdraw',
    'dashboard.riskMitigation': 'Risk and Mitigation',
    'dashboard.legal': 'Legal',
    'dashboard.resetTitle': 'Reset All Investments?',
    'dashboard.resetDescription': 'This will permanently delete all your investments and history. This action cannot be undone.',
    'dashboard.resetWarning': '⚠️ WARNING: do NOT use this function unless strictly authorized by the admin.',
    'dashboard.cancel': 'Cancel',
    'dashboard.reset': 'Reset',
    'dashboard.resetComplete': 'Reset Complete',
    'dashboard.resetSuccess': 'All investments have been cleared.',
    'dashboard.error': 'Error',
    'dashboard.resetFailed': 'Failed to reset investments.',
    'dashboard.apyTitle': 'YOUR ANNUAL PAY YIELD (APY)',
    'dashboard.higherThanBoJ': 'higher than BoJ!',
    'dashboard.feeStructure': 'Fee Structure',
    'dashboard.feeDescription': 'Our management fee is 1% baseline + 20% of the remaining returns.',
    'dashboard.feeExample': 'Example: Asset APY',
    'dashboard.managementFee': 'Management Fee',
    'dashboard.yourAPY': 'Your APY',
    'dashboard.dynamicRate': 'Dynamic Rate',
    'dashboard.dynamicRateDescription': 'This APY updates in real-time based on lending rates across Decentralized Finance (DeFi) protocols and changes constantly with market conditions.',
    'dashboard.loadingAPY': 'Loading APY data...',
    'dashboard.apyError': 'Unable to load APY data',
    'dashboard.pending': 'Pending',
    'dashboard.noInvestments': 'No ongoing investment. Select a desirable good to start having your money work for you.',
    'dashboard.returnsDialogTitle': 'Your Returns',
    'dashboard.returnsDialogDescription': 'View your APY and fee structure details',
    
    // Pick Purchase
    'pickPurchase.title1': 'Select a desirable good to',
    'pickPurchase.title2': 'let your',
    'pickPurchase.title2.money': 'money',
    'pickPurchase.title2.rest': 'work for you',
    'pickPurchase.pick': 'Pick a purchase',
    'pickPurchase.eggs': 'Eggs (10 units)',
    'pickPurchase.milk': 'Milk',
    'pickPurchase.yogurt': 'Yogurt',
    'pickPurchase.beer': 'Beer (6 cans)',
    'pickPurchase.rice': 'Rice (2 kg)',
    'pickPurchase.cigarette': 'Cigarette',
    'pickPurchase.coffee': 'Coffee (Regular)',
    
    // Decide Deposit
    'decideDeposit.title1': 'Select a desirable good to',
    'decideDeposit.title2': 'let your',
    'decideDeposit.title2.money': 'money',
    'decideDeposit.title2.rest': 'work for you',
    'decideDeposit.decide': 'Decide your deposit',
    'decideDeposit.selected': 'Selected Item',
    'decideDeposit.netflix': 'Netflix',
    'decideDeposit.starbucks': 'Starbucks',
    'decideDeposit.eggs': 'Eggs (10 units)',
    'decideDeposit.milk': 'Milk',
    'decideDeposit.yogurt': 'Yogurt',
    'decideDeposit.beer': 'Beer (6 cans)',
    'decideDeposit.rice': 'Rice (2 kg)',
    'decideDeposit.cigarette': 'Cigarette',
    'decideDeposit.coffee': 'Coffee (Regular)',
    'decideDeposit.deposit': 'Deposit',
    'decideDeposit.payback': 'Pay back in',
    'decideDeposit.aiRec': 'AI Recommendation',
    'decideDeposit.nextStep': 'Next step',
    'decideDeposit.addMore': 'Add more recurring purchases',
    'decideDeposit.min': 'Min:',
    'decideDeposit.max': 'Max:',
    'decideDeposit.get': 'Get 1',
    'decideDeposit.free': 'free',
    'decideDeposit.by': 'by',
    'decideDeposit.depositing': 'depositing',
    'decideDeposit.today': 'today',
    'decideDeposit.aiRecText': 'Depositing',
    'decideDeposit.toGetFree': 'to get a free',
    'decideDeposit.eachDay': 'each day',
    'decideDeposit.eachWeek': 'each week',
    'decideDeposit.eachMonth': 'each month',
    'decideDeposit.eachYear': 'each year',
    'decideDeposit.every': 'every',
    'decideDeposit.days': 'days',
    'decideDeposit.months': 'months',
    'decideDeposit.years': 'years',
    
    // Payment Method
    'paymentMethod.title1': 'Select a desirable good to',
    'paymentMethod.title2': 'let your',
    'paymentMethod.title2.money': 'money',
    'paymentMethod.title2.rest': 'work for you',
    'paymentMethod.selectPayment': 'Select payment method',
    'paymentMethod.selected': 'Selected Item',
    'paymentMethod.netflix': 'Netflix',
    'paymentMethod.deposit': 'Deposit',
    'paymentMethod.payback': 'Pay back in',
    'paymentMethod.summary': 'Summary of your offer',
    'paymentMethod.paymentTitle': 'How do you want to deposit?',
    'paymentMethod.bankWire': 'Bank Wire',
    'paymentMethod.stablecoin': 'Stablecoin',
    'paymentMethod.creditCard': 'Credit Card',
    'paymentMethod.get': 'Get 1',
    'paymentMethod.free': 'free',
    'paymentMethod.by': 'by',
    'paymentMethod.depositing': 'depositing',
    'paymentMethod.today': 'today',
    
    // Payment Process
    'paymentProcess.featureAvailable': 'Feature available soon.',
    'paymentProcess.sendUsdc': 'Send',
    'paymentProcess.usdcAmount': 'amount of USDC to the address below.',
    'paymentProcess.finishPayment': 'Finish Payment',
    'paymentProcess.investmentCreated': 'Investment Created!',
    'paymentProcess.investmentCreatedSuccess': 'Your {product} investment has been created successfully.',
    'paymentProcess.error': 'Error',
    'paymentProcess.createFailed': 'Failed to create investment. Please try again.',
    'paymentProcess.investmentUpdated': 'Investment Updated',
    'paymentProcess.addedToInvestment': 'Added ￥{amount} to your {product} investment. Countdown reset.',
    'paymentProcess.withdrawFunds': 'Withdraw Funds',
    'paymentProcess.withdrawDescription': 'Please withdraw ￥{amount} from your existing {product} investment to reduce it.',
    'paymentProcess.noChanges': 'No Changes',
    'paymentProcess.noChangesDescription': 'Your {product} investment amount is the same.',
    'paymentProcess.updateFailed': 'Failed to update investment. Please try again.',
    'paymentProcess.updateExisting': 'Update Existing Investment?',
    'paymentProcess.duplicateDescription': 'You already have an investment for {product} with ￥{amount} deposited. Would you like to update your existing investment?',
    'paymentProcess.cancel': 'Cancel',
    'paymentProcess.update': 'Update',
    
    // Risk Mitigation
    'riskMitigation.title': 'Risk and Mitigation',
    'riskMitigation.intro': 'Welcome to Perkloop. Our service aims to provide high returns by participating in Decentralized Finance (DeFi) lending. Before investing, you must understand the risks as well as our commitment to risk mitigation.',
    'riskMitigation.warning': 'Your principal is NOT insured by the Japanese government or any bank.',
    'riskMitigation.risk1.title': '1. Protocol Exploit Risk',
    'riskMitigation.risk1.description': 'Your money is managed by automated, public software (called smart contracts). Despite significant improvement in security in recent time, flaws in this code can be exploited by hackers, leading to the potential loss of up to 100% of your invested principal.',
    'riskMitigation.risk1.mitigation': 'Mitigation',
    'riskMitigation.risk1.mitigationIntro': 'We establish multiple layers of defense to protect your investment:',
    'riskMitigation.risk1.mitigation1.title': 'Triple Audited System:',
    'riskMitigation.risk1.mitigation1.text': 'We invest in high-quality security audits every quarter and deploy assets across 2-3 separate, highly reputable lending protocols (measured by size and stability) on Sui, a blockchain created by a safe programming language.',
    'riskMitigation.risk1.mitigation2.title': 'Investor Protection Fund (IPF):',
    'riskMitigation.risk1.mitigation2.text': 'We establish the Investor Protection Fund (IPF), backed by our firm\'s segregated capital, to cover 20% of your loss if a hack occurs. This is your immediate safety net.',
    'riskMitigation.risk1.mitigation3.title': 'Commitment to Full Recovery:',
    'riskMitigation.risk1.mitigation3.text': 'In the case of a hack, we will immediately engage with the L1 chain foundation (e.g., the Sui Foundation) and the protocol\'s governance community (DAO), deploying our full legal and technical efforts to lobby for, and maximize the chances of, a community-funded asset recovery or reimbursement. Historically, leading L1 chains and protocols have initiated actions to recover and reimburse lost investor capital, and we commit to acting as your relentless advocate to secure any and all available external recovery.',
    'riskMitigation.risk2.title': '2. Exchange Rate Risk',
    'riskMitigation.risk2.description': 'Your deposit is converted to US Dollar stablecoins to earn yield. If the Japanese Yen strengthens when you withdraw, the amount of JPY you receive back may be less than your original deposit. That said, if Yen weakens when you withdraw, you will receive more Yen than your initial deposit.',
    'riskMitigation.risk2.mitigation': 'Mitigation',
    'riskMitigation.risk2.mitigationText': 'We show you this real-time risk via our Red/Green indicator. You bear this currency risk, but in exchange, you receive the full potential of the high global yield alongside the possibility to gain extra return from currency fluctuations.',
    'riskMitigation.risk3.title': '3. Stablecoin Reserve Risk',
    'riskMitigation.risk3.description': 'Although rare, the stablecoins can lose its peg due to reserve insolvency or banking crises, which can result in the loss of your principal.',
    'riskMitigation.risk3.mitigation': 'Mitigation',
    'riskMitigation.risk3.mitigationText': 'All funds will only be converted to USDC, the single-most secured, compliant, and reputable USD-pegged stablecoin among all, to minimize depegging risks.',
  },
  ja: {
    // Auth
    'auth.welcomeBack': 'おかえりなさい',
    'auth.createAccount': 'アカウント作成',
    'auth.signInSubtitle': 'アカウントにサインイン',
    'auth.signUpSubtitle': 'サインアップして始める',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.enterEmail': 'メールアドレスを入力',
    'auth.enterPassword': 'パスワードを入力',
    'auth.loading': '読み込み中...',
    'auth.signIn': 'サインイン',
    'auth.signUp': 'サインアップ',
    'auth.noAccount': 'アカウントをお持ちでないですか？サインアップ',
    'auth.haveAccount': 'すでにアカウントをお持ちですか？サインイン',
    'auth.testAccount': 'テストアカウント：',
    'auth.error': 'エラー',
    'auth.success': '成功',
    'auth.confirmEmail': 'メールを確認してアカウントを認証してください。',
    
    // Dashboard
    'dashboard.title1': '欲しい商品を選んで',
    'dashboard.title2': 'あなたの',
    'dashboard.title2.money': 'お金',
    'dashboard.title2.rest': 'を働かせましょう',
    'dashboard.withdrawable': '引き出し可能な元本',
    'dashboard.returns': 'リターン',
    'dashboard.investment': '投資進捗',
    'dashboard.days': '日',
    'dashboard.until': '次の無料',
    'dashboard.starbucks': 'スターバックス',
    'dashboard.startInvesting': '投資を始める',
    'dashboard.withdraw': '引き出し',
    'dashboard.riskMitigation': 'リスクと緩和策',
    'dashboard.legal': '法的事項',
    'dashboard.resetTitle': 'すべての投資をリセットしますか？',
    'dashboard.resetDescription': 'これにより、すべての投資と履歴が完全に削除されます。この操作は元に戻せません。',
    'dashboard.resetWarning': '⚠️ 警告：管理者から厳密に許可されている場合を除き、この機能を使用しないでください。',
    'dashboard.cancel': 'キャンセル',
    'dashboard.reset': 'リセット',
    'dashboard.resetComplete': 'リセット完了',
    'dashboard.resetSuccess': 'すべての投資がクリアされました。',
    'dashboard.error': 'エラー',
    'dashboard.resetFailed': '投資のリセットに失敗しました。',
    'dashboard.apyTitle': '年間利回り（APY）',
    'dashboard.higherThanBoJ': '日銀より高い！',
    'dashboard.feeStructure': '手数料体系',
    'dashboard.feeDescription': '管理手数料は基本1%＋残りのリターンの20%です。',
    'dashboard.feeExample': '例：資産APY',
    'dashboard.managementFee': '管理手数料',
    'dashboard.yourAPY': 'あなたのAPY',
    'dashboard.dynamicRate': '動的レート',
    'dashboard.dynamicRateDescription': 'このAPYは、分散型金融（DeFi）プロトコル全体の貸付金利に基づいてリアルタイムで更新され、市場状況に応じて常に変動します。',
    'dashboard.loadingAPY': 'APYデータを読み込み中...',
    'dashboard.apyError': 'APYデータを読み込めません',
    'dashboard.pending': '保留中',
    'dashboard.noInvestments': '進行中の投資はありません。お金を働かせるために、希望する商品を選択してください。',
    'dashboard.returnsDialogTitle': 'あなたのリターン',
    'dashboard.returnsDialogDescription': 'APYと手数料体系の詳細を表示',
    
    // Pick Purchase
    'pickPurchase.title1': '欲しい商品を選んで',
    'pickPurchase.title2': 'あなたの',
    'pickPurchase.title2.money': 'お金',
    'pickPurchase.title2.rest': 'を働かせましょう',
    'pickPurchase.pick': '購入を選択',
    'pickPurchase.eggs': '卵（10個）',
    'pickPurchase.milk': '牛乳',
    'pickPurchase.yogurt': 'ヨーグルト',
    'pickPurchase.beer': 'ビール（6缶）',
    'pickPurchase.rice': '米（2kg）',
    'pickPurchase.cigarette': 'タバコ',
    'pickPurchase.coffee': 'コーヒー（レギュラー）',
    
    // Decide Deposit
    'decideDeposit.title1': '欲しい商品を選んで',
    'decideDeposit.title2': 'あなたの',
    'decideDeposit.title2.money': 'お金',
    'decideDeposit.title2.rest': 'を働かせましょう',
    'decideDeposit.decide': '預金額を決める',
    'decideDeposit.selected': '選択されたアイテム',
    'decideDeposit.netflix': 'ネットフリックス',
    'decideDeposit.starbucks': 'スターバックス',
    'decideDeposit.eggs': '卵（10個）',
    'decideDeposit.milk': '牛乳',
    'decideDeposit.yogurt': 'ヨーグルト',
    'decideDeposit.beer': 'ビール（6缶）',
    'decideDeposit.rice': '米（2kg）',
    'decideDeposit.cigarette': 'タバコ',
    'decideDeposit.coffee': 'コーヒー（レギュラー）',
    'decideDeposit.deposit': '預金',
    'decideDeposit.payback': '返済期間',
    'decideDeposit.aiRec': 'AI推奨',
    'decideDeposit.nextStep': '次のステップ',
    'decideDeposit.addMore': '定期購入を追加',
    'decideDeposit.min': '最小：',
    'decideDeposit.max': '最大：',
    'decideDeposit.get': '',
    'decideDeposit.free': '無料',
    'decideDeposit.by': 'で',
    'decideDeposit.depositing': '',
    'decideDeposit.today': '今日',
    'decideDeposit.aiRecText': '',
    'decideDeposit.toGetFree': 'を預けて無料の',
    'decideDeposit.eachDay': '毎日',
    'decideDeposit.eachWeek': '毎週',
    'decideDeposit.eachMonth': '毎月',
    'decideDeposit.eachYear': '毎年',
    'decideDeposit.every': '毎',
    'decideDeposit.days': '日',
    'decideDeposit.months': 'ヶ月',
    'decideDeposit.years': '年',
    
    // Payment Method
    'paymentMethod.title1': '欲しい商品を選んで',
    'paymentMethod.title2': 'あなたの',
    'paymentMethod.title2.money': 'お金',
    'paymentMethod.title2.rest': 'を働かせましょう',
    'paymentMethod.selectPayment': '決済方法を選択',
    'paymentMethod.selected': '選択されたアイテム',
    'paymentMethod.netflix': 'ネットフリックス',
    'paymentMethod.deposit': '預金',
    'paymentMethod.payback': '返済期間',
    'paymentMethod.summary': 'オファーの概要',
    'paymentMethod.paymentTitle': 'どのように預金しますか？',
    'paymentMethod.bankWire': '銀行送金',
    'paymentMethod.stablecoin': 'ステーブルコイン',
    'paymentMethod.creditCard': 'クレジットカード',
    'paymentMethod.get': '',
    'paymentMethod.free': '無料',
    'paymentMethod.by': 'で',
    'paymentMethod.depositing': '',
    'paymentMethod.today': '今日',
    
    // Payment Process
    'paymentProcess.featureAvailable': '機能は間もなく利用可能です。',
    'paymentProcess.sendUsdc': '',
    'paymentProcess.usdcAmount': 'USDCを以下のアドレスに送金してください。',
    'paymentProcess.finishPayment': '支払いを完了',
    'paymentProcess.investmentCreated': '投資が作成されました！',
    'paymentProcess.investmentCreatedSuccess': '{product}の投資が正常に作成されました。',
    'paymentProcess.error': 'エラー',
    'paymentProcess.createFailed': '投資の作成に失敗しました。もう一度お試しください。',
    'paymentProcess.investmentUpdated': '投資が更新されました',
    'paymentProcess.addedToInvestment': '{product}の投資に￥{amount}を追加しました。カウントダウンがリセットされました。',
    'paymentProcess.withdrawFunds': '資金を引き出す',
    'paymentProcess.withdrawDescription': '既存の{product}投資から￥{amount}を引き出して減額してください。',
    'paymentProcess.noChanges': '変更なし',
    'paymentProcess.noChangesDescription': '{product}の投資額は同じです。',
    'paymentProcess.updateFailed': '投資の更新に失敗しました。もう一度お試しください。',
    'paymentProcess.updateExisting': '既存の投資を更新しますか？',
    'paymentProcess.duplicateDescription': 'すでに{product}の投資があり、￥{amount}が預けられています。既存の投資を更新しますか？',
    'paymentProcess.cancel': 'キャンセル',
    'paymentProcess.update': '更新',
    
    // Risk Mitigation
    'riskMitigation.title': 'リスクと緩和策',
    'riskMitigation.intro': 'Perkloopへようこそ。当サービスは、分散型金融（DeFi）レンディングへの参加により高いリターンを提供することを目指しています。投資する前に、リスクと当社のリスク緩和策について理解する必要があります。',
    'riskMitigation.warning': 'あなたの元本は日本政府や銀行によって保険されていません。',
    'riskMitigation.risk1.title': '1. プロトコル悪用リスク',
    'riskMitigation.risk1.description': 'あなたの資金は自動化された公開ソフトウェア（スマートコントラクト）によって管理されます。近年セキュリティは大幅に改善されていますが、このコードの欠陥がハッカーによって悪用され、投資元本の最大100％を失う可能性があります。',
    'riskMitigation.risk1.mitigation': '緩和策',
    'riskMitigation.risk1.mitigationIntro': '投資を保護するために複数の防御層を確立しています：',
    'riskMitigation.risk1.mitigation1.title': '三重監査システム：',
    'riskMitigation.risk1.mitigation1.text': '四半期ごとに高品質のセキュリティ監査に投資し、安全なプログラミング言語で作成されたブロックチェーンであるSui上の2〜3の別々の高評価レンディングプロトコル（規模と安定性で測定）に資産を展開します。',
    'riskMitigation.risk1.mitigation2.title': '投資家保護基金（IPF）：',
    'riskMitigation.risk1.mitigation2.text': '当社の分離資本に裏付けられた投資家保護基金（IPF）を設立し、ハッキングが発生した場合に損失の20％を補償します。これはあなたの即座の安全網です。',
    'riskMitigation.risk1.mitigation3.title': '完全回復への取り組み：',
    'riskMitigation.risk1.mitigation3.text': 'ハッキングが発生した場合、直ちにL1チェーン財団（例：Sui Foundation）とプロトコルのガバナンスコミュニティ（DAO）に働きかけ、法的・技術的な取り組みを全面的に展開し、コミュニティ資金による資産回復または補償の可能性を最大化します。歴史的に、主要なL1チェーンとプロトコルは失われた投資家資本を回復し補償するための行動を開始しており、私たちはあなたの不屈の代弁者として、利用可能なすべての外部回復を確保することを約束します。',
    'riskMitigation.risk2.title': '2. 為替リスク',
    'riskMitigation.risk2.description': 'あなたの預金は利回りを得るために米ドルステーブルコインに変換されます。引き出し時に日本円が強くなっている場合、受け取る円の金額は元の預金額よりも少なくなる可能性があります。ただし、引き出し時に円が弱くなっている場合は、最初の預金額よりも多くの円を受け取ることができます。',
    'riskMitigation.risk2.mitigation': '緩和策',
    'riskMitigation.risk2.mitigationText': '赤/緑インジケーターを通じてこのリアルタイムリスクを表示します。この通貨リスクを負担する代わりに、高いグローバル利回りの全潜在力と、為替変動から追加のリターンを得る可能性を受け取ります。',
    'riskMitigation.risk3.title': '3. ステーブルコイン準備金リスク',
    'riskMitigation.risk3.description': 'まれではありますが、準備金の破綻や銀行危機により、ステーブルコインがペッグを失い、元本を失う可能性があります。',
    'riskMitigation.risk3.mitigation': '緩和策',
    'riskMitigation.risk3.mitigationText': 'すべての資金はUSDCのみに変換されます。USDCは最も安全で、コンプライアンスに準拠し、評判の高い米ドルペッグステーブルコインであり、ペッグ解除リスクを最小限に抑えます。',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
