// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hobujwfdlijbaswszwnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYnVqd2ZkbGlqYmFzd3N6d25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDg4MTcsImV4cCI6MjA3NDY4NDgxN30.I5MkbmDtqKcdL24kuCI4ki8EBLmaalR6aZ-UFk-vYxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});